services:
  laravel-app:
    build:
      context: .
      dockerfile: dockerFile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ../secure-med-sys:/var/www
    ports:
      - "80:80"

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql

  # Optional Redis Service
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped

# Docker Volumes
volumes:
  dbdata:
