services:
  laravel-app:
    build:
      context: .
      dockerfile: dockerFile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ../secure-medical-app:/var/www
    ports:
      - "8000:80"

  postgres:
    image: postgres:alpine
    container_name: pgsql
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
